"""Time stats

Revision ID: 483fce5a72b9
Revises: 22f8a69b2349
Create Date: 2024-08-05 14:37:53.772495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '483fce5a72b9'
down_revision: Union[str, None] = '22f8a69b2349'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE taskstatus AS ENUM ('PENDING', 'IN_WORK', 'DONE')")
    op.add_column('tasks', sa.Column('status', sa.Enum('PENDING', 'IN_WORK', 'DONE', name='taskstatus'), nullable=False))
    op.add_column('tasks', sa.Column('time_spent', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('end_time', sa.DateTime(), nullable=True))
    op.drop_column('tasks', 'done')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('done', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('tasks', 'end_time')
    op.drop_column('tasks', 'start_time')
    op.drop_column('tasks', 'time_spent')
    op.drop_column('tasks', 'status')
    op.execute('DROP TYPE taskstatus')
    # ### end Alembic commands ###
